package com.nf.manage.dao.bean;

public class JpushData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_data.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_data.passport_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Long passportId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_data.jpush_config_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer jpushConfigId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_data.state
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_data.ts
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Long ts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_data.id
	 * @return  the value of jpush_data.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_data.id
	 * @param id  the value for jpush_data.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_data.passport_id
	 * @return  the value of jpush_data.passport_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Long getPassportId() {
		return passportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_data.passport_id
	 * @param passportId  the value for jpush_data.passport_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setPassportId(Long passportId) {
		this.passportId = passportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_data.jpush_config_id
	 * @return  the value of jpush_data.jpush_config_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getJpushConfigId() {
		return jpushConfigId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_data.jpush_config_id
	 * @param jpushConfigId  the value for jpush_data.jpush_config_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setJpushConfigId(Integer jpushConfigId) {
		this.jpushConfigId = jpushConfigId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_data.state
	 * @return  the value of jpush_data.state
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_data.state
	 * @param state  the value for jpush_data.state
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_data.ts
	 * @return  the value of jpush_data.ts
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Long getTs() {
		return ts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_data.ts
	 * @param ts  the value for jpush_data.ts
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setTs(Long ts) {
		this.ts = ts;
	}
}