package com.nf.manage.dao.bean;

import java.util.ArrayList;
import java.util.List;

public class JpushDataExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public JpushDataExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPassportIdIsNull() {
			addCriterion("passport_id is null");
			return (Criteria) this;
		}

		public Criteria andPassportIdIsNotNull() {
			addCriterion("passport_id is not null");
			return (Criteria) this;
		}

		public Criteria andPassportIdEqualTo(Long value) {
			addCriterion("passport_id =", value, "passportId");
			return (Criteria) this;
		}

		public Criteria andPassportIdNotEqualTo(Long value) {
			addCriterion("passport_id <>", value, "passportId");
			return (Criteria) this;
		}

		public Criteria andPassportIdGreaterThan(Long value) {
			addCriterion("passport_id >", value, "passportId");
			return (Criteria) this;
		}

		public Criteria andPassportIdGreaterThanOrEqualTo(Long value) {
			addCriterion("passport_id >=", value, "passportId");
			return (Criteria) this;
		}

		public Criteria andPassportIdLessThan(Long value) {
			addCriterion("passport_id <", value, "passportId");
			return (Criteria) this;
		}

		public Criteria andPassportIdLessThanOrEqualTo(Long value) {
			addCriterion("passport_id <=", value, "passportId");
			return (Criteria) this;
		}

		public Criteria andPassportIdIn(List<Long> values) {
			addCriterion("passport_id in", values, "passportId");
			return (Criteria) this;
		}

		public Criteria andPassportIdNotIn(List<Long> values) {
			addCriterion("passport_id not in", values, "passportId");
			return (Criteria) this;
		}

		public Criteria andPassportIdBetween(Long value1, Long value2) {
			addCriterion("passport_id between", value1, value2, "passportId");
			return (Criteria) this;
		}

		public Criteria andPassportIdNotBetween(Long value1, Long value2) {
			addCriterion("passport_id not between", value1, value2, "passportId");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdIsNull() {
			addCriterion("jpush_config_id is null");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdIsNotNull() {
			addCriterion("jpush_config_id is not null");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdEqualTo(Integer value) {
			addCriterion("jpush_config_id =", value, "jpushConfigId");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdNotEqualTo(Integer value) {
			addCriterion("jpush_config_id <>", value, "jpushConfigId");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdGreaterThan(Integer value) {
			addCriterion("jpush_config_id >", value, "jpushConfigId");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("jpush_config_id >=", value, "jpushConfigId");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdLessThan(Integer value) {
			addCriterion("jpush_config_id <", value, "jpushConfigId");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdLessThanOrEqualTo(Integer value) {
			addCriterion("jpush_config_id <=", value, "jpushConfigId");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdIn(List<Integer> values) {
			addCriterion("jpush_config_id in", values, "jpushConfigId");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdNotIn(List<Integer> values) {
			addCriterion("jpush_config_id not in", values, "jpushConfigId");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdBetween(Integer value1, Integer value2) {
			addCriterion("jpush_config_id between", value1, value2, "jpushConfigId");
			return (Criteria) this;
		}

		public Criteria andJpushConfigIdNotBetween(Integer value1, Integer value2) {
			addCriterion("jpush_config_id not between", value1, value2, "jpushConfigId");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("state is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("state is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(Integer value) {
			addCriterion("state =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(Integer value) {
			addCriterion("state <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(Integer value) {
			addCriterion("state >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("state >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(Integer value) {
			addCriterion("state <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(Integer value) {
			addCriterion("state <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<Integer> values) {
			addCriterion("state in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<Integer> values) {
			addCriterion("state not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(Integer value1, Integer value2) {
			addCriterion("state between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(Integer value1, Integer value2) {
			addCriterion("state not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andTsIsNull() {
			addCriterion("ts is null");
			return (Criteria) this;
		}

		public Criteria andTsIsNotNull() {
			addCriterion("ts is not null");
			return (Criteria) this;
		}

		public Criteria andTsEqualTo(Long value) {
			addCriterion("ts =", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsNotEqualTo(Long value) {
			addCriterion("ts <>", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsGreaterThan(Long value) {
			addCriterion("ts >", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsGreaterThanOrEqualTo(Long value) {
			addCriterion("ts >=", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsLessThan(Long value) {
			addCriterion("ts <", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsLessThanOrEqualTo(Long value) {
			addCriterion("ts <=", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsIn(List<Long> values) {
			addCriterion("ts in", values, "ts");
			return (Criteria) this;
		}

		public Criteria andTsNotIn(List<Long> values) {
			addCriterion("ts not in", values, "ts");
			return (Criteria) this;
		}

		public Criteria andTsBetween(Long value1, Long value2) {
			addCriterion("ts between", value1, value2, "ts");
			return (Criteria) this;
		}

		public Criteria andTsNotBetween(Long value1, Long value2) {
			addCriterion("ts not between", value1, value2, "ts");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table jpush_data
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jpush_data
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 16 11:20:01 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}