package com.nf.manage.dao.bean;

public class MailSubscribeConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_subscribe_config.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_subscribe_config.subcribe_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer subcribeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_subscribe_config.mail_address
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String mailAddress;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_subscribe_config.id
	 * @return  the value of mail_subscribe_config.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_subscribe_config.id
	 * @param id  the value for mail_subscribe_config.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_subscribe_config.subcribe_id
	 * @return  the value of mail_subscribe_config.subcribe_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getSubcribeId() {
		return subcribeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_subscribe_config.subcribe_id
	 * @param subcribeId  the value for mail_subscribe_config.subcribe_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setSubcribeId(Integer subcribeId) {
		this.subcribeId = subcribeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_subscribe_config.mail_address
	 * @return  the value of mail_subscribe_config.mail_address
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getMailAddress() {
		return mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_subscribe_config.mail_address
	 * @param mailAddress  the value for mail_subscribe_config.mail_address
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}
}