package com.nf.manage.dao.bean;

public class ServerConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_config.server_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String serverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_config.desc
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_config.ip
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_config.port
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer port;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_config.priviledge_pswd
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String priviledgePswd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_config.group_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_config.type
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_config.order
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer order;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_config.state
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_config.server_id
	 * @return  the value of server_config.server_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getServerId() {
		return serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_config.server_id
	 * @param serverId  the value for server_config.server_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setServerId(String serverId) {
		this.serverId = serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_config.desc
	 * @return  the value of server_config.desc
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_config.desc
	 * @param desc  the value for server_config.desc
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_config.ip
	 * @return  the value of server_config.ip
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_config.ip
	 * @param ip  the value for server_config.ip
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_config.port
	 * @return  the value of server_config.port
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_config.port
	 * @param port  the value for server_config.port
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_config.priviledge_pswd
	 * @return  the value of server_config.priviledge_pswd
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getPriviledgePswd() {
		return priviledgePswd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_config.priviledge_pswd
	 * @param priviledgePswd  the value for server_config.priviledge_pswd
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setPriviledgePswd(String priviledgePswd) {
		this.priviledgePswd = priviledgePswd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_config.group_id
	 * @return  the value of server_config.group_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_config.group_id
	 * @param groupId  the value for server_config.group_id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_config.type
	 * @return  the value of server_config.type
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_config.type
	 * @param type  the value for server_config.type
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_config.order
	 * @return  the value of server_config.order
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getOrder() {
		return order;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_config.order
	 * @param order  the value for server_config.order
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setOrder(Integer order) {
		this.order = order;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_config.state
	 * @return  the value of server_config.state
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_config.state
	 * @param state  the value for server_config.state
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setState(Integer state) {
		this.state = state;
	}
}