package com.nf.manage.dao.bean;

import java.util.ArrayList;
import java.util.List;

public class ServerConfigExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public ServerConfigExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andServerIdIsNull() {
			addCriterion("server_id is null");
			return (Criteria) this;
		}

		public Criteria andServerIdIsNotNull() {
			addCriterion("server_id is not null");
			return (Criteria) this;
		}

		public Criteria andServerIdEqualTo(String value) {
			addCriterion("server_id =", value, "serverId");
			return (Criteria) this;
		}

		public Criteria andServerIdNotEqualTo(String value) {
			addCriterion("server_id <>", value, "serverId");
			return (Criteria) this;
		}

		public Criteria andServerIdGreaterThan(String value) {
			addCriterion("server_id >", value, "serverId");
			return (Criteria) this;
		}

		public Criteria andServerIdGreaterThanOrEqualTo(String value) {
			addCriterion("server_id >=", value, "serverId");
			return (Criteria) this;
		}

		public Criteria andServerIdLessThan(String value) {
			addCriterion("server_id <", value, "serverId");
			return (Criteria) this;
		}

		public Criteria andServerIdLessThanOrEqualTo(String value) {
			addCriterion("server_id <=", value, "serverId");
			return (Criteria) this;
		}

		public Criteria andServerIdLike(String value) {
			addCriterion("server_id like", value, "serverId");
			return (Criteria) this;
		}

		public Criteria andServerIdNotLike(String value) {
			addCriterion("server_id not like", value, "serverId");
			return (Criteria) this;
		}

		public Criteria andServerIdIn(List<String> values) {
			addCriterion("server_id in", values, "serverId");
			return (Criteria) this;
		}

		public Criteria andServerIdNotIn(List<String> values) {
			addCriterion("server_id not in", values, "serverId");
			return (Criteria) this;
		}

		public Criteria andServerIdBetween(String value1, String value2) {
			addCriterion("server_id between", value1, value2, "serverId");
			return (Criteria) this;
		}

		public Criteria andServerIdNotBetween(String value1, String value2) {
			addCriterion("server_id not between", value1, value2, "serverId");
			return (Criteria) this;
		}

		public Criteria andDescIsNull() {
			addCriterion("desc is null");
			return (Criteria) this;
		}

		public Criteria andDescIsNotNull() {
			addCriterion("desc is not null");
			return (Criteria) this;
		}

		public Criteria andDescEqualTo(String value) {
			addCriterion("desc =", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotEqualTo(String value) {
			addCriterion("desc <>", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescGreaterThan(String value) {
			addCriterion("desc >", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescGreaterThanOrEqualTo(String value) {
			addCriterion("desc >=", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescLessThan(String value) {
			addCriterion("desc <", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescLessThanOrEqualTo(String value) {
			addCriterion("desc <=", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescLike(String value) {
			addCriterion("desc like", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotLike(String value) {
			addCriterion("desc not like", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescIn(List<String> values) {
			addCriterion("desc in", values, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotIn(List<String> values) {
			addCriterion("desc not in", values, "desc");
			return (Criteria) this;
		}

		public Criteria andDescBetween(String value1, String value2) {
			addCriterion("desc between", value1, value2, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotBetween(String value1, String value2) {
			addCriterion("desc not between", value1, value2, "desc");
			return (Criteria) this;
		}

		public Criteria andIpIsNull() {
			addCriterion("ip is null");
			return (Criteria) this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("ip is not null");
			return (Criteria) this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("ip =", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("ip <>", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("ip >", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("ip >=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("ip <", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("ip <=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("ip like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("ip not like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("ip in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("ip not in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("ip between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("ip not between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andPortIsNull() {
			addCriterion("port is null");
			return (Criteria) this;
		}

		public Criteria andPortIsNotNull() {
			addCriterion("port is not null");
			return (Criteria) this;
		}

		public Criteria andPortEqualTo(Integer value) {
			addCriterion("port =", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotEqualTo(Integer value) {
			addCriterion("port <>", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortGreaterThan(Integer value) {
			addCriterion("port >", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortGreaterThanOrEqualTo(Integer value) {
			addCriterion("port >=", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortLessThan(Integer value) {
			addCriterion("port <", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortLessThanOrEqualTo(Integer value) {
			addCriterion("port <=", value, "port");
			return (Criteria) this;
		}

		public Criteria andPortIn(List<Integer> values) {
			addCriterion("port in", values, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotIn(List<Integer> values) {
			addCriterion("port not in", values, "port");
			return (Criteria) this;
		}

		public Criteria andPortBetween(Integer value1, Integer value2) {
			addCriterion("port between", value1, value2, "port");
			return (Criteria) this;
		}

		public Criteria andPortNotBetween(Integer value1, Integer value2) {
			addCriterion("port not between", value1, value2, "port");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdIsNull() {
			addCriterion("priviledge_pswd is null");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdIsNotNull() {
			addCriterion("priviledge_pswd is not null");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdEqualTo(String value) {
			addCriterion("priviledge_pswd =", value, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdNotEqualTo(String value) {
			addCriterion("priviledge_pswd <>", value, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdGreaterThan(String value) {
			addCriterion("priviledge_pswd >", value, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdGreaterThanOrEqualTo(String value) {
			addCriterion("priviledge_pswd >=", value, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdLessThan(String value) {
			addCriterion("priviledge_pswd <", value, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdLessThanOrEqualTo(String value) {
			addCriterion("priviledge_pswd <=", value, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdLike(String value) {
			addCriterion("priviledge_pswd like", value, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdNotLike(String value) {
			addCriterion("priviledge_pswd not like", value, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdIn(List<String> values) {
			addCriterion("priviledge_pswd in", values, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdNotIn(List<String> values) {
			addCriterion("priviledge_pswd not in", values, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdBetween(String value1, String value2) {
			addCriterion("priviledge_pswd between", value1, value2, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andPriviledgePswdNotBetween(String value1, String value2) {
			addCriterion("priviledge_pswd not between", value1, value2, "priviledgePswd");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNull() {
			addCriterion("group_id is null");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNotNull() {
			addCriterion("group_id is not null");
			return (Criteria) this;
		}

		public Criteria andGroupIdEqualTo(Integer value) {
			addCriterion("group_id =", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotEqualTo(Integer value) {
			addCriterion("group_id <>", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThan(Integer value) {
			addCriterion("group_id >", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("group_id >=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThan(Integer value) {
			addCriterion("group_id <", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThanOrEqualTo(Integer value) {
			addCriterion("group_id <=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIn(List<Integer> values) {
			addCriterion("group_id in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotIn(List<Integer> values) {
			addCriterion("group_id not in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdBetween(Integer value1, Integer value2) {
			addCriterion("group_id between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotBetween(Integer value1, Integer value2) {
			addCriterion("group_id not between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andOrderIsNull() {
			addCriterion("order is null");
			return (Criteria) this;
		}

		public Criteria andOrderIsNotNull() {
			addCriterion("order is not null");
			return (Criteria) this;
		}

		public Criteria andOrderEqualTo(Integer value) {
			addCriterion("order =", value, "order");
			return (Criteria) this;
		}

		public Criteria andOrderNotEqualTo(Integer value) {
			addCriterion("order <>", value, "order");
			return (Criteria) this;
		}

		public Criteria andOrderGreaterThan(Integer value) {
			addCriterion("order >", value, "order");
			return (Criteria) this;
		}

		public Criteria andOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("order >=", value, "order");
			return (Criteria) this;
		}

		public Criteria andOrderLessThan(Integer value) {
			addCriterion("order <", value, "order");
			return (Criteria) this;
		}

		public Criteria andOrderLessThanOrEqualTo(Integer value) {
			addCriterion("order <=", value, "order");
			return (Criteria) this;
		}

		public Criteria andOrderIn(List<Integer> values) {
			addCriterion("order in", values, "order");
			return (Criteria) this;
		}

		public Criteria andOrderNotIn(List<Integer> values) {
			addCriterion("order not in", values, "order");
			return (Criteria) this;
		}

		public Criteria andOrderBetween(Integer value1, Integer value2) {
			addCriterion("order between", value1, value2, "order");
			return (Criteria) this;
		}

		public Criteria andOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("order not between", value1, value2, "order");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("state is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("state is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(Integer value) {
			addCriterion("state =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(Integer value) {
			addCriterion("state <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(Integer value) {
			addCriterion("state >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("state >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(Integer value) {
			addCriterion("state <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(Integer value) {
			addCriterion("state <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<Integer> values) {
			addCriterion("state in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<Integer> values) {
			addCriterion("state not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(Integer value1, Integer value2) {
			addCriterion("state between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(Integer value1, Integer value2) {
			addCriterion("state not between", value1, value2, "state");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table server_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table server_config
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 11 16:40:46 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}