package com.nf.manage.dao.bean;

public class TClubGiftRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column texas..t_club_gift_record.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column texas..t_club_gift_record.clubId
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String clubid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column texas..t_club_gift_record.senderPassportId
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Long senderpassportid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column texas..t_club_gift_record.ts
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Long ts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column texas..t_club_gift_record.id
	 * @return  the value of texas..t_club_gift_record.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column texas..t_club_gift_record.id
	 * @param id  the value for texas..t_club_gift_record.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column texas..t_club_gift_record.clubId
	 * @return  the value of texas..t_club_gift_record.clubId
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getClubid() {
		return clubid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column texas..t_club_gift_record.clubId
	 * @param clubid  the value for texas..t_club_gift_record.clubId
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setClubid(String clubid) {
		this.clubid = clubid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column texas..t_club_gift_record.senderPassportId
	 * @return  the value of texas..t_club_gift_record.senderPassportId
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Long getSenderpassportid() {
		return senderpassportid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column texas..t_club_gift_record.senderPassportId
	 * @param senderpassportid  the value for texas..t_club_gift_record.senderPassportId
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setSenderpassportid(Long senderpassportid) {
		this.senderpassportid = senderpassportid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column texas..t_club_gift_record.ts
	 * @return  the value of texas..t_club_gift_record.ts
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Long getTs() {
		return ts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column texas..t_club_gift_record.ts
	 * @param ts  the value for texas..t_club_gift_record.ts
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setTs(Long ts) {
		this.ts = ts;
	}
}