/*
 * JSP generated by Resin-3.0.19 (built Mon, 15 May 2006 04:50:47 PDT)
 */

package _jsp._texas._server;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;

public class _server_0list__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_1.print(out, pageContext, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_2.print(out, pageContext, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
      if (_jsp_loop_0 == null)
        _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
      java.util.Iterator _jsp_iter_1 = com.caucho.jstl.el.ForEachTag.getIterator(_caucho_expr_3.evalObject(pageContext));
      _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
      Object _jsp_status_1 = pageContext.putAttribute("status", _jsp_loop_0);
      Object _jsp_oldVar_1 = pageContext.getAttribute("server");
      while (_jsp_iter_1.hasNext()) {
        Object _jsp_i_1 = _jsp_iter_1.next();
        pageContext.setAttribute("server", _jsp_i_1);
        _jsp_loop_0.setCurrent(_jsp_i_1, _jsp_iter_1.hasNext());
        out.write(_jsp_string4, 0, _jsp_string4.length);
        _caucho_expr_4.print(out, pageContext, false);
        out.write(_jsp_string5, 0, _jsp_string5.length);
        _caucho_expr_5.print(out, pageContext, false);
        out.write(_jsp_string5, 0, _jsp_string5.length);
        _caucho_expr_6.print(out, pageContext, false);
        out.write(_jsp_string5, 0, _jsp_string5.length);
        _caucho_expr_7.print(out, pageContext, false);
        out.write(_jsp_string6, 0, _jsp_string6.length);
        if (_caucho_expr_8.evalBoolean(pageContext)) {
          out.write(_jsp_string7, 0, _jsp_string7.length);
        }
        out.write(_jsp_string8, 0, _jsp_string8.length);
        if (_caucho_expr_9.evalBoolean(pageContext)) {
          out.write(_jsp_string9, 0, _jsp_string9.length);
        }
        out.write(_jsp_string8, 0, _jsp_string8.length);
        if (_caucho_expr_10.evalBoolean(pageContext)) {
          out.write(_jsp_string10, 0, _jsp_string10.length);
        }
        out.write(_jsp_string11, 0, _jsp_string11.length);
        if (_caucho_expr_11.evalBoolean(pageContext)) {
          out.write(_jsp_string12, 0, _jsp_string12.length);
          _caucho_expr_4.print(out, pageContext, false);
          out.write(_jsp_string13, 0, _jsp_string13.length);
        }
        out.write(_jsp_string14, 0, _jsp_string14.length);
        if (_caucho_expr_8.evalBoolean(pageContext)) {
          out.write(_jsp_string15, 0, _jsp_string15.length);
          _caucho_expr_4.print(out, pageContext, false);
          out.write(_jsp_string16, 0, _jsp_string16.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
      }
      pageContext.pageSetOrRemove("server", _jsp_oldVar_1);
      pageContext.pageSetOrRemove("status", _jsp_status_1);
      out.write(_jsp_string18, 0, _jsp_string18.length);
      pageContext.include("/common/page.jsp", true);
      out.write(_jsp_string19, 0, _jsp_string19.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 7932908523769947432L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("texas/server/server_list.jsp"), -4871627408013905134L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.IdExpr("account");
  private final static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.IdExpr("username");
  private final static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.IdExpr("G_url");
  private final static com.caucho.el.Expr _caucho_expr_3 =
    new com.caucho.el.IdExpr("servers");
  private final static com.caucho.el.Expr _caucho_expr_4 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("server"), new com.caucho.el.StringLiteral("serverId")), "server.serverId");
  private final static com.caucho.el.Expr _caucho_expr_5 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("server"), new com.caucho.el.StringLiteral("ip")), "server.ip");
  private final static com.caucho.el.Expr _caucho_expr_6 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("server"), new com.caucho.el.StringLiteral("port")), "server.port");
  private final static com.caucho.el.Expr _caucho_expr_7 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("server"), new com.caucho.el.StringLiteral("nums")), "server.nums");
  private final static com.caucho.el.Expr _caucho_expr_8 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("server"), new com.caucho.el.StringLiteral("status")), "server.status"), new com.caucho.el.LongLiteral(1L));
  private final static com.caucho.el.Expr _caucho_expr_9 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("server"), new com.caucho.el.StringLiteral("status")), "server.status"), new com.caucho.el.LongLiteral(0L));
  private final static com.caucho.el.Expr _caucho_expr_10 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("server"), new com.caucho.el.StringLiteral("status")), "server.status"), new com.caucho.el.LongLiteral(2L));
  private final static com.caucho.el.Expr _caucho_expr_11 =
    new com.caucho.el.EqExpr(7, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("server"), new com.caucho.el.StringLiteral("status")), "server.status"), new com.caucho.el.LongLiteral(1L));

  private final static char []_jsp_string1;
  private final static char []_jsp_string16;
  private final static char []_jsp_string5;
  private final static char []_jsp_string12;
  private final static char []_jsp_string19;
  private final static char []_jsp_string4;
  private final static char []_jsp_string9;
  private final static char []_jsp_string0;
  private final static char []_jsp_string6;
  private final static char []_jsp_string8;
  private final static char []_jsp_string3;
  private final static char []_jsp_string15;
  private final static char []_jsp_string11;
  private final static char []_jsp_string7;
  private final static char []_jsp_string10;
  private final static char []_jsp_string13;
  private final static char []_jsp_string17;
  private final static char []_jsp_string2;
  private final static char []_jsp_string18;
  private final static char []_jsp_string14;
  static {
    _jsp_string1 = "\"  id=\"account\" ></input>				\r\n				<label >Username</label>\r\n				<input type=\"text\" class=\"input-medium\" value=\"".toCharArray();
    _jsp_string16 = "')\">\u8f6c\u4e3a\u6d4b\u8bd5</button>\r\n						".toCharArray();
    _jsp_string5 = "</td>\r\n					<td>".toCharArray();
    _jsp_string12 = "							\r\n							<button class='btn btn-mini btn-info' onclick=\"removeTest('".toCharArray();
    _jsp_string19 = "\r\n		\r\n	</div>	\r\n</div>\r\n<div id=\"ami_newwindow\" style=\"display: none;\">\r\n\r\n</div>\r\n\r\n<script type=\"text/javascript\">\r\n\r\nfunction doTest(id)\r\n{\r\n	bootbox.confirm(\"\u786e\u5b9a\u8981\u8f6c\u4e3a\u6d4b\u8bd5\u670d\u4e48?\", function(result) {\r\n		if(result) {\r\n			\r\n			$('.ami_Mask').show();\r\n			var url=\"server.do?method=update&serverId=\"+id+\"&state=0\";\r\n			$.post(url, function(data){\r\n				$('.ami_Mask').hide();\r\n				bootbox.alert(\"data\");						\r\n			});						\r\n		}\r\n	});		\r\n}\r\n\r\nfunction removeTest(id)\r\n{\r\n	bootbox.confirm(\"\u786e\u5b9a\u8fd0\u884c\u670d\u52a1\u5668?\", function(result) {\r\n		if(result) {\r\n			\r\n			$('.ami_Mask').show();\r\n			var url=\"server.do?method=update&serverId=\"+id+\"&state=1\";\r\n			$.post(url, function(data){\r\n				$('.ami_Mask').hide();\r\n				bootbox.alert(\"data\");						\r\n			});						\r\n		}\r\n	});		\r\n}\r\n</script>".toCharArray();
    _jsp_string4 = "\r\n					\r\n				<tr>\r\n					<td>".toCharArray();
    _jsp_string9 = "\r\n					<td>\u6d4b\u8bd5\u4e2d</td>\r\n				".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<div id=\"ami_main\">\r\n<div class=\"row-fluid\">	\r\n			<form class=\"form-inline\" action=\"game.do?method=queryNews\" id=\"searchForm\">\r\n				<label>Useraccount</label>\r\n				<input  type=\"text\" class=\"input-medium\"  name=\"useraccount\" value=\"".toCharArray();
    _jsp_string6 = "</td>\r\n				".toCharArray();
    _jsp_string8 = "\r\n				".toCharArray();
    _jsp_string3 = "\">\r\n		<table id=\"table_report\" class=\"table table-striped table-bordered table-hover\">\r\n			<thead>			\r\n				<tr>\r\n					<th>Server ID</th>\r\n					<th>IP Address</th>\r\n					<th>Port</th>\r\n					<th>Nums</th>\r\n					<th>Status</th>\r\n					<th>\u7ba1\u7406</th>\r\n				</tr>				\r\n			</thead>\r\n			<tbody>				\r\n			 ".toCharArray();
    _jsp_string15 = "\r\n							<button class='btn btn-mini btn-info' onclick=\"doTest('".toCharArray();
    _jsp_string11 = "\r\n\r\n					<td>\r\n						<div class='hidden-phone visible-desktop btn-group'>\r\n						".toCharArray();
    _jsp_string7 = "\r\n					<td>\u8fd0\u884c\u4e2d</td>\r\n				".toCharArray();
    _jsp_string10 = "\r\n					<td>\u5df2\u505c\u673a</td>\r\n				".toCharArray();
    _jsp_string13 = "')\">\u8f6c\u4e3a\u8fd0\u884c</button>\r\n						".toCharArray();
    _jsp_string17 = "					\r\n						</div>\r\n					</td>\r\n				</tr>\r\n				\r\n			  ".toCharArray();
    _jsp_string2 = "\" name=\"username\"  ></input>\r\n				<button type=\"button\"  style=\"margin-left:10px\" class=\"btn btn-mini btn-info\" onClick=\"go(1)\">\u68c0\u7d22</button>\r\n			</form>\r\n</div>	\r\n<hr/>\r\n\r\n<div class=\"row-fluid\">\r\n	\r\n		<div class=\"ami_table_header\"><span class=\"ami_table_header_title\">\u670d\u52a1\u5668\u5217\u8868</span>\r\n\r\n		</div>\r\n		<input type=\"hidden\" name=\"server\" value=\"".toCharArray();
    _jsp_string18 = "\r\n					\r\n			</tbody>\r\n		</table>		\r\n		".toCharArray();
    _jsp_string14 = "\r\n						".toCharArray();
  }
}
