/*
 * JSP generated by Resin-3.0.19 (built Mon, 15 May 2006 04:50:47 PDT)
 */

package _jsp._texas._log;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;

public class _log_0list__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_1.print(out, pageContext, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_2.print(out, pageContext, false);
      out.write(_jsp_string4, 0, _jsp_string4.length);
      _caucho_expr_3.print(out, pageContext, false);
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_4.print(out, pageContext, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string7, 0, _jsp_string7.length);
      if (_caucho_expr_5.evalBoolean(pageContext)) {
        out.write(_jsp_string8, 0, _jsp_string8.length);
      }
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if (_caucho_expr_6.evalBoolean(pageContext)) {
        out.write(_jsp_string10, 0, _jsp_string10.length);
      }
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if (_caucho_expr_7.evalBoolean(pageContext)) {
        out.write(_jsp_string11, 0, _jsp_string11.length);
      }
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if (_caucho_expr_8.evalBoolean(pageContext)) {
        out.write(_jsp_string12, 0, _jsp_string12.length);
      }
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if (_caucho_expr_9.evalBoolean(pageContext)) {
        out.write(_jsp_string13, 0, _jsp_string13.length);
      }
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if (_caucho_expr_10.evalBoolean(pageContext)) {
        out.write(_jsp_string14, 0, _jsp_string14.length);
      }
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if (_caucho_expr_11.evalBoolean(pageContext)) {
        out.write(_jsp_string15, 0, _jsp_string15.length);
      }
      out.write(_jsp_string16, 0, _jsp_string16.length);
      if (_caucho_expr_12.evalBoolean(pageContext)) {
        out.write(_jsp_string17, 0, _jsp_string17.length);
      }
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if (_caucho_expr_13.evalBoolean(pageContext)) {
        out.write(_jsp_string18, 0, _jsp_string18.length);
      }
      out.write(_jsp_string19, 0, _jsp_string19.length);
      if (_caucho_expr_14.evalBoolean(pageContext)) {
        out.write(_jsp_string20, 0, _jsp_string20.length);
      }
      out.write(_jsp_string21, 0, _jsp_string21.length);
      if (_jsp_loop_0 == null)
        _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
      java.util.Iterator _jsp_iter_1 = com.caucho.jstl.el.ForEachTag.getIterator(_caucho_expr_15.evalObject(pageContext));
      _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
      Object _jsp_status_1 = pageContext.putAttribute("status", _jsp_loop_0);
      Object _jsp_oldVar_1 = pageContext.getAttribute("user");
      while (_jsp_iter_1.hasNext()) {
        Object _jsp_i_1 = _jsp_iter_1.next();
        pageContext.setAttribute("user", _jsp_i_1);
        _jsp_loop_0.setCurrent(_jsp_i_1, _jsp_iter_1.hasNext());
        out.write(_jsp_string22, 0, _jsp_string22.length);
        _caucho_expr_16.print(out, pageContext, false);
        out.write(_jsp_string23, 0, _jsp_string23.length);
        _caucho_expr_17.print(out, pageContext, false);
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _caucho_expr_18.print(out, pageContext, false);
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _caucho_expr_19.print(out, pageContext, false);
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _caucho_expr_20.print(out, pageContext, false);
        out.write(_jsp_string25, 0, _jsp_string25.length);
        _caucho_expr_0.print(out, pageContext, false);
        out.write(_jsp_string26, 0, _jsp_string26.length);
        _caucho_expr_21.print(out, pageContext, false);
        out.write(_jsp_string27, 0, _jsp_string27.length);
        _caucho_expr_21.print(out, pageContext, false);
        out.write(_jsp_string28, 0, _jsp_string28.length);
        _caucho_expr_22.print(out, pageContext, false);
        out.write(_jsp_string24, 0, _jsp_string24.length);
        _caucho_expr_23.print(out, pageContext, false);
        out.write(_jsp_string29, 0, _jsp_string29.length);
        if (_caucho_expr_5.evalBoolean(pageContext)) {
          out.write(_jsp_string30, 0, _jsp_string30.length);
          _caucho_expr_24.print(out, pageContext, false);
          out.write(_jsp_string31, 0, _jsp_string31.length);
          _caucho_expr_25.print(out, pageContext, false);
          out.write(_jsp_string31, 0, _jsp_string31.length);
          _caucho_expr_26.print(out, pageContext, false);
          out.write(_jsp_string32, 0, _jsp_string32.length);
        }
        out.write(_jsp_string19, 0, _jsp_string19.length);
        if (_caucho_expr_6.evalBoolean(pageContext)) {
          out.write(_jsp_string33, 0, _jsp_string33.length);
          _caucho_expr_27.print(out, pageContext, false);
          out.write(_jsp_string34, 0, _jsp_string34.length);
          _caucho_expr_28.print(out, pageContext, false);
          out.write(_jsp_string35, 0, _jsp_string35.length);
        }
        out.write(_jsp_string9, 0, _jsp_string9.length);
        if (_caucho_expr_7.evalBoolean(pageContext)) {
          out.write(_jsp_string33, 0, _jsp_string33.length);
          _caucho_expr_29.print(out, pageContext, false);
          out.write(_jsp_string34, 0, _jsp_string34.length);
          _caucho_expr_30.print(out, pageContext, false);
          out.write(_jsp_string35, 0, _jsp_string35.length);
        }
        out.write(_jsp_string9, 0, _jsp_string9.length);
        if (_caucho_expr_8.evalBoolean(pageContext)) {
          out.write(_jsp_string33, 0, _jsp_string33.length);
          _caucho_expr_31.print(out, pageContext, false);
          out.write(_jsp_string35, 0, _jsp_string35.length);
        }
        out.write(_jsp_string9, 0, _jsp_string9.length);
        if (_caucho_expr_9.evalBoolean(pageContext)) {
          out.write(_jsp_string33, 0, _jsp_string33.length);
          _caucho_expr_32.print(out, pageContext, false);
          out.write(_jsp_string35, 0, _jsp_string35.length);
        }
        out.write(_jsp_string9, 0, _jsp_string9.length);
        if (_caucho_expr_10.evalBoolean(pageContext)) {
          out.write(_jsp_string33, 0, _jsp_string33.length);
          _caucho_expr_33.print(out, pageContext, false);
          out.write(_jsp_string34, 0, _jsp_string34.length);
          _caucho_expr_34.print(out, pageContext, false);
          out.write(_jsp_string35, 0, _jsp_string35.length);
        }
        out.write(_jsp_string9, 0, _jsp_string9.length);
        if (_caucho_expr_11.evalBoolean(pageContext)) {
          out.write(_jsp_string33, 0, _jsp_string33.length);
          _caucho_expr_35.print(out, pageContext, false);
          out.write(_jsp_string34, 0, _jsp_string34.length);
          _caucho_expr_36.print(out, pageContext, false);
          out.write(_jsp_string35, 0, _jsp_string35.length);
        }
        out.write(_jsp_string16, 0, _jsp_string16.length);
        if (_caucho_expr_12.evalBoolean(pageContext)) {
          out.write(_jsp_string33, 0, _jsp_string33.length);
          _caucho_expr_37.print(out, pageContext, false);
          out.write(_jsp_string34, 0, _jsp_string34.length);
          _caucho_expr_38.print(out, pageContext, false);
          out.write(_jsp_string34, 0, _jsp_string34.length);
          _caucho_expr_39.print(out, pageContext, false);
          out.write(_jsp_string35, 0, _jsp_string35.length);
        }
        out.write(_jsp_string9, 0, _jsp_string9.length);
        if (_caucho_expr_13.evalBoolean(pageContext)) {
          out.write(_jsp_string33, 0, _jsp_string33.length);
          _caucho_expr_37.print(out, pageContext, false);
          out.write(_jsp_string35, 0, _jsp_string35.length);
        }
        out.write(_jsp_string19, 0, _jsp_string19.length);
        if (_caucho_expr_14.evalBoolean(pageContext)) {
          out.write(_jsp_string33, 0, _jsp_string33.length);
          _caucho_expr_37.print(out, pageContext, false);
          out.write(_jsp_string35, 0, _jsp_string35.length);
        }
        out.write(_jsp_string36, 0, _jsp_string36.length);
        if (_caucho_expr_40.evalBoolean(pageContext)) {
          out.write(_jsp_string37, 0, _jsp_string37.length);
          _caucho_expr_41.print(out, pageContext, false);
          out.write(_jsp_string38, 0, _jsp_string38.length);
        }
        else {
          out.write(_jsp_string39, 0, _jsp_string39.length);
          _caucho_expr_41.print(out, pageContext, false);
          out.write(_jsp_string38, 0, _jsp_string38.length);
        }
        out.write(_jsp_string40, 0, _jsp_string40.length);
        _caucho_expr_42.print(out, pageContext, false);
        out.write(_jsp_string41, 0, _jsp_string41.length);
        _caucho_expr_43.print(out, pageContext, false);
        out.write(_jsp_string42, 0, _jsp_string42.length);
      }
      pageContext.pageSetOrRemove("user", _jsp_oldVar_1);
      pageContext.pageSetOrRemove("status", _jsp_status_1);
      out.write(_jsp_string43, 0, _jsp_string43.length);
      pageContext.include("/common/page.jsp", true);
      out.write(_jsp_string44, 0, _jsp_string44.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 7932908523769947432L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("texas/log/log_list.jsp"), -1809359890779285743L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("type")), "params.type");
  private final static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("date")), "params.date");
  private final static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("start")), "params.start");
  private final static com.caucho.el.Expr _caucho_expr_3 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("end")), "params.end");
  private final static com.caucho.el.Expr _caucho_expr_4 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("account_id")), "params.account_id");
  private final static com.caucho.el.Expr _caucho_expr_5 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("type")), "params.type"), new com.caucho.el.StringLiteral("chat"));
  private final static com.caucho.el.Expr _caucho_expr_6 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("type")), "params.type"), new com.caucho.el.StringLiteral("gold"));
  private final static com.caucho.el.Expr _caucho_expr_7 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("type")), "params.type"), new com.caucho.el.StringLiteral("diamond"));
  private final static com.caucho.el.Expr _caucho_expr_8 =
    new com.caucho.el.BooleanExpr(13, new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("type")), "params.type"), new com.caucho.el.StringLiteral("monthcard")), new com.caucho.el.EqExpr(6, new com.caucho.el.IdExpr("type"), new com.caucho.el.StringLiteral("weekcard")));
  private final static com.caucho.el.Expr _caucho_expr_9 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("type")), "params.type"), new com.caucho.el.StringLiteral("vip"));
  private final static com.caucho.el.Expr _caucho_expr_10 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("type")), "params.type"), new com.caucho.el.StringLiteral("recharge"));
  private final static com.caucho.el.Expr _caucho_expr_11 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("type")), "params.type"), new com.caucho.el.StringLiteral("sign_in"));
  private final static com.caucho.el.Expr _caucho_expr_12 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("type")), "params.type"), new com.caucho.el.StringLiteral("texas_room"));
  private final static com.caucho.el.Expr _caucho_expr_13 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("type")), "params.type"), new com.caucho.el.StringLiteral("baccarat_room"));
  private final static com.caucho.el.Expr _caucho_expr_14 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("params"), new com.caucho.el.StringLiteral("type")), "params.type"), new com.caucho.el.StringLiteral("slot_room"));
  private final static com.caucho.el.Expr _caucho_expr_15 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("PAGER"), new com.caucho.el.StringLiteral("items")), "PAGER.items");
  private final static com.caucho.el.Expr _caucho_expr_16 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("id")), "user.id");
  private final static com.caucho.el.Expr _caucho_expr_17 =
    new com.caucho.el.BinaryExpr(1, new com.caucho.el.BinaryExpr(1, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("status"), new com.caucho.el.StringLiteral("index")), "status.index"), new com.caucho.el.LongLiteral(1L)), new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("PAGER"), new com.caucho.el.StringLiteral("start")), "PAGER.start"));
  private final static com.caucho.el.Expr _caucho_expr_18 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("log_type")), "user.log_type");
  private final static com.caucho.el.Expr _caucho_expr_19 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("log_date")), "user.log_date");
  private final static com.caucho.el.Expr _caucho_expr_20 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("create_date")), "user.create_date");
  private final static com.caucho.el.Expr _caucho_expr_21 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("account_id")), "user.account_id");
  private final static com.caucho.el.Expr _caucho_expr_22 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("account_name")), "user.account_name");
  private final static com.caucho.el.Expr _caucho_expr_23 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("level")), "user.level");
  private final static com.caucho.el.Expr _caucho_expr_24 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("channel")), "user.channel");
  private final static com.caucho.el.Expr _caucho_expr_25 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("rec_char_name")), "user.rec_char_name");
  private final static com.caucho.el.Expr _caucho_expr_26 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("content")), "user.content");
  private final static com.caucho.el.Expr _caucho_expr_27 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("gold_delta")), "user.gold_delta");
  private final static com.caucho.el.Expr _caucho_expr_28 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("gold_left")), "user.gold_left");
  private final static com.caucho.el.Expr _caucho_expr_29 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("diamond_delta")), "user.diamond_delta");
  private final static com.caucho.el.Expr _caucho_expr_30 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("diamond_left")), "user.diamond_left");
  private final static com.caucho.el.Expr _caucho_expr_31 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("duration_day")), "user.duration_day");
  private final static com.caucho.el.Expr _caucho_expr_32 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("vip_level")), "user.vip_level");
  private final static com.caucho.el.Expr _caucho_expr_33 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("order_id")), "user.order_id");
  private final static com.caucho.el.Expr _caucho_expr_34 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("product_id")), "user.product_id");
  private final static com.caucho.el.Expr _caucho_expr_35 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("days")), "user.days");
  private final static com.caucho.el.Expr _caucho_expr_36 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("culumative")), "user.culumative");
  private final static com.caucho.el.Expr _caucho_expr_37 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("room_id")), "user.room_id");
  private final static com.caucho.el.Expr _caucho_expr_38 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("mode_id")), "user.mode_id");
  private final static com.caucho.el.Expr _caucho_expr_39 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("type_id")), "user.type_id");
  private final static com.caucho.el.Expr _caucho_expr_40 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("reason")), "user.reason"), new com.caucho.el.LongLiteral(0L));
  private final static com.caucho.el.Expr _caucho_expr_41 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("reason")), "user.reason");
  private final static com.caucho.el.Expr _caucho_expr_42 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("region_id")), "user.region_id");
  private final static com.caucho.el.Expr _caucho_expr_43 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("param")), "user.param");

  private final static char []_jsp_string9;
  private final static char []_jsp_string24;
  private final static char []_jsp_string12;
  private final static char []_jsp_string23;
  private final static char []_jsp_string4;
  private final static char []_jsp_string26;
  private final static char []_jsp_string25;
  private final static char []_jsp_string7;
  private final static char []_jsp_string38;
  private final static char []_jsp_string22;
  private final static char []_jsp_string39;
  private final static char []_jsp_string11;
  private final static char []_jsp_string1;
  private final static char []_jsp_string36;
  private final static char []_jsp_string15;
  private final static char []_jsp_string16;
  private final static char []_jsp_string18;
  private final static char []_jsp_string17;
  private final static char []_jsp_string28;
  private final static char []_jsp_string42;
  private final static char []_jsp_string43;
  private final static char []_jsp_string14;
  private final static char []_jsp_string29;
  private final static char []_jsp_string5;
  private final static char []_jsp_string27;
  private final static char []_jsp_string34;
  private final static char []_jsp_string8;
  private final static char []_jsp_string31;
  private final static char []_jsp_string33;
  private final static char []_jsp_string19;
  private final static char []_jsp_string41;
  private final static char []_jsp_string30;
  private final static char []_jsp_string20;
  private final static char []_jsp_string44;
  private final static char []_jsp_string2;
  private final static char []_jsp_string10;
  private final static char []_jsp_string21;
  private final static char []_jsp_string3;
  private final static char []_jsp_string13;
  private final static char []_jsp_string32;
  private final static char []_jsp_string37;
  private final static char []_jsp_string35;
  private final static char []_jsp_string40;
  private final static char []_jsp_string0;
  private final static char []_jsp_string6;
  static {
    _jsp_string9 = "\r\n					\r\n					".toCharArray();
    _jsp_string24 = "</td>\r\n					<td>".toCharArray();
    _jsp_string12 = "\r\n						<th>\u6301\u7eed\u65f6\u95f4(\u5929\u6570)</th>\r\n					".toCharArray();
    _jsp_string23 = "\">\r\n				\r\n					<td>".toCharArray();
    _jsp_string4 = "\" >		\r\n					--\r\n					<input class=\"form-control\" name=\"end\" id=\"end_time\" style=\"width:60px\" value=\"".toCharArray();
    _jsp_string26 = "&account_id=".toCharArray();
    _jsp_string25 = "</td>\r\n					<td><a onclick=\"openNewWinow('log.do?method=queryLog&type=".toCharArray();
    _jsp_string7 = " Logs</span>\r\n\r\n		</div>\r\n		<table id=\"table_report\" class=\"table table-striped table-bordered table-hover\">\r\n			<thead>			\r\n				<tr>\r\n				<th>No.</th>\r\n					<th>\u65e5\u5fd7\u7c7b\u578b</th>\r\n					<th>\u65f6\u95f4</th>\r\n					<th>\u521b\u5efa\u65f6\u95f4</th>\r\n					<th>\u73a9\u5bb6\u8d26\u53f7ID</th>\r\n					<th>\u73a9\u5bb6\u8d26\u53f7\u540d</th>\r\n					<th>\u7b49\u7ea7</th>\r\n					\r\n					".toCharArray();
    _jsp_string38 = "</td>\r\n							  ".toCharArray();
    _jsp_string22 = "\r\n					\r\n				<tr id=\"tr_".toCharArray();
    _jsp_string39 = "\r\n							  <td class=\"cloro-DarkGoldenrod\">".toCharArray();
    _jsp_string11 = "\r\n						<th>\u5e73\u53f0\u5e01\u53d8\u5316</th>\r\n						<th>\u5e73\u53f0\u5e01\u5269\u4f59</th>\r\n					".toCharArray();
    _jsp_string1 = "\" id=\"searchForm\">\r\n\r\n					<input type=\"hidden\" name=\"type\" value=\"".toCharArray();
    _jsp_string36 = "\r\n					\r\n						\r\n					".toCharArray();
    _jsp_string15 = "\r\n						<th>\u8fde\u7eed\u7b7e\u5230</th>\r\n						<th>\u7d2f\u8ba1\u7b7e\u5230</th>\r\n					".toCharArray();
    _jsp_string16 = "\r\n										\r\n					".toCharArray();
    _jsp_string18 = "\r\n						<th>\u623f\u95f4ID</th>\r\n					".toCharArray();
    _jsp_string17 = "\r\n						<th>\u623f\u95f4ID</th>\r\n						<th>\u6a21\u5f0fID</th>\r\n						<th>\u7c7b\u578bID</th>\r\n					".toCharArray();
    _jsp_string28 = "</a></td>\r\n					<td>".toCharArray();
    _jsp_string42 = "</td>\r\n					\r\n				</tr>\r\n				\r\n			  ".toCharArray();
    _jsp_string43 = "\r\n					\r\n			</tbody>\r\n		</table>		\r\n		".toCharArray();
    _jsp_string14 = "\r\n						<th>\u8ba2\u5355\u53f7</th>\r\n						<th>\u4ea7\u54c1\u7f16\u53f7</th>\r\n					".toCharArray();
    _jsp_string29 = "</td>\r\n					\r\n					".toCharArray();
    _jsp_string5 = "\"/>\r\n					\r\n					<label>\u73a9\u5bb6\u8d26\u53f7ID</label>\r\n					<input class=\"input-medium\" style=\"width: 100px\" name=\"account_id\" value=\"".toCharArray();
    _jsp_string27 = "')\">".toCharArray();
    _jsp_string34 = "</th>\r\n						<th>".toCharArray();
    _jsp_string8 = "\r\n						<th>\u9891\u9053</th>\r\n						<th>\u63a5\u53d7\u8005\u540d\u5b57</th>\r\n						<th>\u5185\u5bb9</th>\r\n					".toCharArray();
    _jsp_string31 = "</td>\r\n						<td>".toCharArray();
    _jsp_string33 = "\r\n						<th>".toCharArray();
    _jsp_string19 = "\r\n					".toCharArray();
    _jsp_string41 = "</td>\r\n					\r\n					<td>".toCharArray();
    _jsp_string30 = "\r\n						<td>".toCharArray();
    _jsp_string20 = "\r\n						<th>\u8001\u864e\u673aID</th>\r\n					".toCharArray();
    _jsp_string44 = "\r\n		\r\n	</div>	\r\n</div>\r\n<div id=\"ami_newwindow\" style=\"display: none;\">\r\n\r\n</div>\r\n<script type=\"text/javascript\" src=\"/js/Clockpicker/bootstrap-clockpicker.min.js\"></script>\r\n<script type=\"text/javascript\">\r\n$('#start_time').clockpicker({\r\n    placement: 'bottom',\r\n    align: 'left',\r\n    autoclose: true\r\n});\r\n$('#end_time').clockpicker({\r\n    placement: 'bottom',\r\n    align: 'left',\r\n    autoclose: true\r\n});\r\n</script>".toCharArray();
    _jsp_string2 = "\"/>\r\n					<label>\u65e5\u671f\uff1a</label>\r\n			  		<input type=\"text\" id=\"d4312\" name=\"date\" value=\"".toCharArray();
    _jsp_string10 = "\r\n						<th>\u7b79\u7801\u53d8\u5316</th>\r\n						<th>\u7b79\u7801\u5269\u4f59</th>\r\n					".toCharArray();
    _jsp_string21 = "\r\n					\r\n					<th>\u539f\u56e0</th>						\r\n					<th>\u533aID</th>\r\n					<th>\u5907\u6ce8</th>\r\n			\r\n				</tr>				\r\n			</thead>\r\n			<tbody>				\r\n			 ".toCharArray();
    _jsp_string3 = "\"  class=\"Wdate\"  onClick=\"WdatePicker({startDate:'%y-%M-01 00',dateFmt:'yyyy_MM_dd'})\" /> \r\n					\r\n					<label>\u9009\u62e9\u65f6\u95f4\u6bb5\uff1a</label>\r\n					\r\n					<input class=\"form-control\" name=\"start\" id=\"start_time\" style=\"width:60px\" value=\"".toCharArray();
    _jsp_string13 = "\r\n						<th>vip\u7b49\u7ea7</th>\r\n					".toCharArray();
    _jsp_string32 = "</td>\r\n					".toCharArray();
    _jsp_string37 = "\r\n							  <td class=\"cloro-Goldenrod\">".toCharArray();
    _jsp_string35 = "</th>\r\n					".toCharArray();
    _jsp_string40 = "					\r\n					<td>".toCharArray();
    _jsp_string0 = "<!-- Log \u9875\u9762 -->\r\n\r\n\r\n\r\n\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/js/Clockpicker/bootstrap-clockpicker.min.css\">\r\n<style>\r\n.cloro-Goldenrod{\r\nbackground:#DC143C;\r\ncolor:#fff;\r\n}\r\n.cloro-DarkGoldenrod{\r\nbackground:#2E8B57;\r\ncolor:#fff;\r\n}\r\n</style>\r\n<div id=\"ami_main\">\r\n	<div class=\"row-fluid\" id=\"div1\">	\r\n			<form class=\"form-inline\" action=\"log.do?method=queryLog&type=".toCharArray();
    _jsp_string6 = "\"></input>\r\n					<button type=\"button\"  style=\"margin-left:10px\" class=\"btn btn-mini btn-info\" onClick=\"go(1)\">\u68c0\u7d22</button>\r\n			</form>\r\n	</div>\r\n<hr/>\r\n\r\n<div class=\"row-fluid\">\r\n	\r\n		<div class=\"ami_table_header\"><span class=\"ami_table_header_title\">".toCharArray();
  }
}
