/*
 * JSP generated by Resin-3.0.19 (built Mon, 15 May 2006 04:50:47 PDT)
 */

package _jsp._adminlog;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;

public class _adminlog_0logrecord__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_1.print(out, pageContext, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_jsp_loop_0 == null)
        _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
      java.util.Iterator _jsp_iter_1 = com.caucho.jstl.el.ForEachTag.getIterator(_caucho_expr_2.evalObject(pageContext));
      _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
      Object _jsp_status_1 = pageContext.putAttribute("status", _jsp_loop_0);
      Object _jsp_oldVar_1 = pageContext.getAttribute("user");
      while (_jsp_iter_1.hasNext()) {
        Object _jsp_i_1 = _jsp_iter_1.next();
        pageContext.setAttribute("user", _jsp_i_1);
        _jsp_loop_0.setCurrent(_jsp_i_1, _jsp_iter_1.hasNext());
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _caucho_expr_3.print(out, pageContext, false);
        out.write(_jsp_string4, 0, _jsp_string4.length);
        if (_caucho_expr_4.evalBoolean(pageContext)) {
          out.write(_jsp_string5, 0, _jsp_string5.length);
        }
        _caucho_expr_5.print(out, pageContext, false);
        out.write(_jsp_string6, 0, _jsp_string6.length);
        _caucho_expr_6.print(out, pageContext, false);
        out.write(_jsp_string6, 0, _jsp_string6.length);
        _caucho_expr_7.print(out, pageContext, false);
        out.write(_jsp_string7, 0, _jsp_string7.length);
        _caucho_expr_8.print(out, pageContext, false);
        out.write(_jsp_string6, 0, _jsp_string6.length);
        _caucho_expr_9.print(out, pageContext, false);
        out.write(_jsp_string8, 0, _jsp_string8.length);
      }
      pageContext.pageSetOrRemove("user", _jsp_oldVar_1);
      pageContext.pageSetOrRemove("status", _jsp_status_1);
      out.write(_jsp_string9, 0, _jsp_string9.length);
      pageContext.include("/common/page.jsp", true);
      out.write(_jsp_string10, 0, _jsp_string10.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 7932908523769947432L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("adminlog/adminlog_logrecord.jsp"), -3766409542589317645L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.IdExpr("login_time");
  private final static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.IdExpr("logout_time");
  private final static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("PAGER"), new com.caucho.el.StringLiteral("items")), "PAGER.items");
  private final static com.caucho.el.Expr _caucho_expr_3 =
    new com.caucho.el.BinaryExpr(1, new com.caucho.el.BinaryExpr(1, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("status"), new com.caucho.el.StringLiteral("index")), "status.index"), new com.caucho.el.LongLiteral(1L)), new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("PAGER"), new com.caucho.el.StringLiteral("start")), "PAGER.start"));
  private final static com.caucho.el.Expr _caucho_expr_4 =
    new com.caucho.el.UnaryExpr(16, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("adminid")), "user.adminid"));
  private final static com.caucho.el.Expr _caucho_expr_5 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("adminid")), "user.adminid");
  private final static com.caucho.el.Expr _caucho_expr_6 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("username")), "user.username");
  private final static com.caucho.el.Expr _caucho_expr_7 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("remoteip")), "user.remoteip");
  private final static com.caucho.el.Expr _caucho_expr_8 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("oprate")), "user.oprate");
  private final static com.caucho.el.Expr _caucho_expr_9 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("user"), new com.caucho.el.StringLiteral("time_stamp")), "user.time_stamp");

  private final static char []_jsp_string6;
  private final static char []_jsp_string7;
  private final static char []_jsp_string9;
  private final static char []_jsp_string2;
  private final static char []_jsp_string5;
  private final static char []_jsp_string10;
  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string8;
  private final static char []_jsp_string3;
  static {
    _jsp_string6 = "</td>\r\n	                <td>".toCharArray();
    _jsp_string7 = "</td>\r\n					<td>".toCharArray();
    _jsp_string9 = "\r\n				\r\n			</tbody>\r\n		</table>		\r\n		".toCharArray();
    _jsp_string2 = "\"  class=\"Wdate\" style=\"width: 150px;margin-right: 10px;padding-left: 5px\" onClick=\"WdatePicker({minDate:'#F{$dp.$D(\\'d4311\\')}',startDate:'%y-%M-01 00:00:00',dateFmt:'yyyy-MM-dd HH:mm:ss'})\" /> \r\n\r\n\r\n           	<button type=\"button\"  style=\"margin-left:10px\" class=\"btn btn-mini btn-info\" onclick=\"go(1)\">\u68c0\u7d22</button>\r\n		</form>\r\n	</div>\r\n<div class=\"row-fluid\">	\r\n		<div class=\"ami_table_header\"><span class=\"ami_table_header_title\">\u65e5\u5fd7\u5217\u8868</span></div>\r\n		<table id=\"table_report\" class=\"table table-striped table-bordered table-hover\">\r\n			<thead>\r\n				<tr>\r\n					<th>\u5e8f\u53f7</th>\r\n					<th>\u8d26\u53f7</th>\r\n					<th>\u59d3\u540d</th>\r\n					<th>IP</th>\r\n					<th>\u64cd\u4f5c\u5185\u5bb9</th>\r\n                    <th>\u64cd\u4f5c\u65f6\u95f4</th>\r\n				</tr>				\r\n			</thead>\r\n			<tbody>				\r\n			\r\n				  ".toCharArray();
    _jsp_string5 = "<span class=\"red\">N/A</span>".toCharArray();
    _jsp_string10 = "\r\n		\r\n	</div>	\r\n</div>\r\n<div id=\"ami_newwindow\" style=\"display: none;\">\r\n\r\n</div>\r\n\r\n\r\n<script type=\"text/javascript\" src=\"js/bootbox.min.js\"></script>\r\n\r\n\r\n<script type=\"text/javascript\">\r\n$('[data-rel=tooltip]').tooltip();\r\nfunction go(page)\r\n{\r\n	var params = $('#searchForm').formSerialize();\r\n	\r\n	var url = $('#searchForm').attr('action') +\"&currentPage=\"+page;\r\n	$.post(url,params,function (data){\r\n	\r\n	$('#PAGECONTENT').html(data);	\r\n	});\r\n}\r\n</script>".toCharArray();
    _jsp_string4 = "</td>					\r\n					<td>".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<div id=\"ami_main\">\r\n<div class=\"page-header position-relative\">\r\n		<form class=\"form-inline\" action=\"adminLog.do?method=toQuery_logrecord\" id=\"searchForm\">		\r\n            \r\n       		   \u8d77\u59cb\uff1a<input type=\"text\"  id=\"d4311\" name=\"login_time\" value=\"".toCharArray();
    _jsp_string1 = "\"  class=\"Wdate\" style=\"width: 150px;margin-right: 10px;padding-left: 5px\" onClick=\"WdatePicker({maxDate:'#F{$dp.$D(\\'d4312\\')}',startDate:'%y-%M-01 00:00:00',dateFmt:'yyyy-MM-dd HH:mm:ss'})\" />\r\n			    \u7ed3\u675f\uff1a<input type=\"text\" id=\"d4312\" name=\"logout_time\" value=\"".toCharArray();
    _jsp_string8 = "</td>\r\n				</tr>\r\n				\r\n			  ".toCharArray();
    _jsp_string3 = "\r\n				<tr>\r\n					<td>".toCharArray();
  }
}
