package com.nf.manage.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.nf.manage.dao.bean.MailSubscribeConfig;
import com.nf.manage.dao.bean.MailSubscribeConfigExample;

public interface MailSubscribeConfigMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_subscribe_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	long countByExample(MailSubscribeConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_subscribe_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	int deleteByExample(MailSubscribeConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_subscribe_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_subscribe_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	int insert(MailSubscribeConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_subscribe_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	int insertSelective(MailSubscribeConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_subscribe_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	List<MailSubscribeConfig> selectByExample(MailSubscribeConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_subscribe_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	MailSubscribeConfig selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_subscribe_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	int updateByExampleSelective(@Param("record") MailSubscribeConfig record,
			@Param("example") MailSubscribeConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_subscribe_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	int updateByExample(@Param("record") MailSubscribeConfig record,
			@Param("example") MailSubscribeConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_subscribe_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	int updateByPrimaryKeySelective(MailSubscribeConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_subscribe_config
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	int updateByPrimaryKey(MailSubscribeConfig record);
}