/*
 * JSP generated by Resin-3.0.19 (built Mon, 15 May 2006 04:50:47 PDT)
 */

package _jsp._googlemap;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _googlemap__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 7932908523769947432L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("googlemap/googlemap.jsp"), 6654088211520166785L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.IdExpr("obj");

  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  static {
    _jsp_string2 = "';\r\n\r\n\r\nfunction initialize() { \r\n		/* var latlng = new google.maps.LatLng(31.253313, 121.241581);  */\r\n		var latlng = new google.maps.LatLng(31.253313, 121.241581);  \r\n		var myOptions ={ \r\n				zoom: 10, //\u7f29\u653e\u7ea7\u522b\r\n				center: latlng, //\u5750\u6807\r\n				mapTypeId: google.maps.MapTypeId.ROADMAP //\u7c7b\u578b:\u9ed8\u8ba4\u7684\u666e\u901a\u4e8c\u7ef4\u56fe\u5757\r\n		}; \r\n		map = new google.maps.Map(document.getElementById(\"googleMap\"), myOptions); //\u7ebf\u6761\u8bbe\u7f6e\r\n\r\n		var polyOptions ={ \r\n					strokeColor: '#FF0000', //\u989c\u8272\r\n					strokeOpacity: 1.0, //\u900f\u660e\u5ea6\r\n					strokeWeight: 4 //\u5bbd\u5ea6\r\n				} \r\n		poly = new google.maps.Polyline(polyOptions);\r\n		/* poly.setMap(map); //\u88c5\u8f7d */\r\n\r\n		/*\u5faa\u73af\u6807\u51fa\u6240\u6709\u5750\u6807 */\r\n		for(var i=0; i<locations.length; i++){ \r\n			var loc = locations[i].split(','); \r\n			var path = poly.getPath(); //\u83b7\u53d6\u7ebf\u6761\u7684\u5750\u6807\r\n		    path.push(new google.maps.LatLng(loc[0], loc[1])); //\u4e3a\u7ebf\u6761\u6dfb\u52a0\u6807\u8bb0\u5750\u6807\r\n		//\u751f\u6210\u6807\u8bb0\u56fe\u6807\r\n			marker = new google.maps.Marker({\r\n				position: new google.maps.LatLng(loc[0], loc[1]), \r\n				map: map, \r\n				icon: \"http://labs.google.com/ridefinder/images/mm_20_green.png\"\r\n			}); \r\n		} \r\n		\r\n}\r\ngoogle.maps.event.addDomListener(window, 'load', initialize);\r\n</script>\r\n</head>\r\n \r\n<div id=\"googleMap\" style=\"width:1700px;height:800px;\"></div>\r\n \r\n".toCharArray();
    _jsp_string0 = "\r\n<script src=\"http://maps.googleapis.com/maps/api/js?key=AIzaSyCuMB--kvTJG29_maJlBDUfEAuYW8_K50M&sensor=false\">\r\n</script>\r\n \r\n<script>\r\n\r\n//\u6240\u6709\u5750\u6807\r\n\r\n/* var locations = new Array( \"31.953313,121.841581\",\r\n							\"31.15347,121.291706\", \r\n							\"31.207516,121.412556\",\r\n							\"31.122909,121.458561\", \r\n							\"31.118207,121.38715\",\r\n							\"31.041168,121.426289\",\r\n							\"39.9289,116.3883\",\r\n							\"30.985262,121.301319\",\r\n							\"31.057934,121.305834\"); */\r\nvar obj = eval('".toCharArray();
    _jsp_string1 = "');\r\nvar locations = [];\r\nfor(var i=0;i<obj.length;i++){\r\n	var single = obj[i];\r\n	locations[i]=single.latitude+\",\"+single.longitude;\r\n}\r\n//var locations = '".toCharArray();
  }
}
