package com.nf.manage.dao.bean;

public class JpushConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_config.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_config.jpush_type
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer jpushType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_config.description
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_config.title
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_config.content
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_config.priority
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private Integer priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_config.notification_type
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String notificationType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_config.send_time
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String sendTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jpush_config.filter_params
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	private String filterParams;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_config.id
	 * @return  the value of jpush_config.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_config.id
	 * @param id  the value for jpush_config.id
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_config.jpush_type
	 * @return  the value of jpush_config.jpush_type
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getJpushType() {
		return jpushType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_config.jpush_type
	 * @param jpushType  the value for jpush_config.jpush_type
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setJpushType(Integer jpushType) {
		this.jpushType = jpushType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_config.description
	 * @return  the value of jpush_config.description
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_config.description
	 * @param description  the value for jpush_config.description
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_config.title
	 * @return  the value of jpush_config.title
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_config.title
	 * @param title  the value for jpush_config.title
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_config.content
	 * @return  the value of jpush_config.content
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_config.content
	 * @param content  the value for jpush_config.content
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_config.priority
	 * @return  the value of jpush_config.priority
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_config.priority
	 * @param priority  the value for jpush_config.priority
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_config.notification_type
	 * @return  the value of jpush_config.notification_type
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getNotificationType() {
		return notificationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_config.notification_type
	 * @param notificationType  the value for jpush_config.notification_type
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setNotificationType(String notificationType) {
		this.notificationType = notificationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_config.send_time
	 * @return  the value of jpush_config.send_time
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getSendTime() {
		return sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_config.send_time
	 * @param sendTime  the value for jpush_config.send_time
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setSendTime(String sendTime) {
		this.sendTime = sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jpush_config.filter_params
	 * @return  the value of jpush_config.filter_params
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public String getFilterParams() {
		return filterParams;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jpush_config.filter_params
	 * @param filterParams  the value for jpush_config.filter_params
	 * @mbg.generated  Mon Sep 18 23:04:08 CST 2017
	 */
	public void setFilterParams(String filterParams) {
		this.filterParams = filterParams;
	}
}