/*
 * JSP generated by Resin-3.0.19 (built Mon, 15 May 2006 04:50:47 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _header__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 7932908523769947432L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("header.jsp"), 8887975667682255896L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("_loginInfo"), new com.caucho.el.StringLiteral("username")), "_loginInfo.username");

  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  static {
    _jsp_string1 = "</span> <i class=\"icon-caret-down\"></i> </a>\r\n          <ul class=\"user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer\">\r\n            <li> <a href=\"###\" onclick=\"nav('/admin/admin_modpwd.jsp?1=1',title)\" > <i class=\"icon-user\"></i> \u4fee\u6539\u5bc6\u7801 </a> </li>\r\n            <li class=\"divider\"></li>\r\n            <li> <a href=\"login.do?method=loginOut\"> <i class=\"icon-off\"></i> Logout </a> </li>\r\n          </ul>\r\n        </li>\r\n        \r\n        \r\n      </ul>\r\n      <!--/.ace-nav-->\r\n    </div>\r\n    <!--/.container-fluid-->\r\n  </div>\r\n  <!--/.navbar-inner-->\r\n</div>\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<div class=\"navbar\">\r\n  <div class=\"navbar-inner\">\r\n    <div class=\"container-fluid\"><img alt=\"\" src=\"img/logo.png\"  style=\"height: 59px;\">  <b style=\"color:#FFFFFF;font-size:30px;\">Paparich\u540e\u53f0\u7ba1\u7406\u7cfb\u7edf</b>\r\n      <!--/.brand-->\r\n      <ul class=\"nav ace-nav pull-right\">\r\n        \r\n        \r\n       \r\n        <li class=\"light-blue\" > <a data-toggle=\"dropdown\" href=\"#\" class=\"dropdown-toggle\"> <span class=\"user-info\">".toCharArray();
  }
}
