/*
 * JSP generated by Resin-3.0.19 (built Mon, 15 May 2006 04:50:47 PDT)
 */

package _jsp._texas._feedback;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _feedback_0list__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_loop_0 == null)
        _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
      java.util.Iterator _jsp_iter_1 = com.caucho.jstl.el.ForEachTag.getIterator(_caucho_expr_0.evalObject(pageContext));
      _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
      Object _jsp_status_1 = pageContext.putAttribute("status", _jsp_loop_0);
      Object _jsp_oldVar_1 = pageContext.getAttribute("one");
      while (_jsp_iter_1.hasNext()) {
        Object _jsp_i_1 = _jsp_iter_1.next();
        pageContext.setAttribute("one", _jsp_i_1);
        _jsp_loop_0.setCurrent(_jsp_i_1, _jsp_iter_1.hasNext());
        out.write(_jsp_string1, 0, _jsp_string1.length);
        _caucho_expr_1.print(out, pageContext, false);
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_1.print(out, pageContext, false);
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _caucho_expr_1.print(out, pageContext, false);
        out.write(_jsp_string4, 0, _jsp_string4.length);
        _caucho_expr_2.print(out, pageContext, false);
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _caucho_expr_2.print(out, pageContext, false);
        out.write(_jsp_string5, 0, _jsp_string5.length);
        _caucho_expr_3.print(out, pageContext, false);
        out.write(_jsp_string6, 0, _jsp_string6.length);
        _caucho_expr_2.print(out, pageContext, false);
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _caucho_expr_3.print(out, pageContext, false);
        out.write(_jsp_string7, 0, _jsp_string7.length);
        _caucho_expr_1.print(out, pageContext, false);
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _caucho_expr_4.print(out, pageContext, false);
        out.write(_jsp_string8, 0, _jsp_string8.length);
        _caucho_expr_5.print(out, pageContext, false);
        out.write(_jsp_string9, 0, _jsp_string9.length);
        if (_caucho_expr_6.evalBoolean(pageContext)) {
          out.write(_jsp_string10, 0, _jsp_string10.length);
          _caucho_expr_1.print(out, pageContext, false);
          out.write(_jsp_string11, 0, _jsp_string11.length);
        }
        out.write(_jsp_string12, 0, _jsp_string12.length);
        if (_caucho_expr_7.evalBoolean(pageContext)) {
          out.write(_jsp_string13, 0, _jsp_string13.length);
          _caucho_expr_1.print(out, pageContext, false);
          out.write(_jsp_string11, 0, _jsp_string11.length);
        }
        out.write(_jsp_string12, 0, _jsp_string12.length);
        if (_caucho_expr_8.evalBoolean(pageContext)) {
          out.write(_jsp_string14, 0, _jsp_string14.length);
        }
        out.write(_jsp_string15, 0, _jsp_string15.length);
        _caucho_expr_9.print(out, pageContext, false);
        out.write(_jsp_string16, 0, _jsp_string16.length);
        _caucho_expr_1.print(out, pageContext, false);
        out.write(_jsp_string17, 0, _jsp_string17.length);
      }
      pageContext.pageSetOrRemove("one", _jsp_oldVar_1);
      pageContext.pageSetOrRemove("status", _jsp_status_1);
      out.write(_jsp_string18, 0, _jsp_string18.length);
      pageContext.include("/common/page.jsp", true);
      out.write(_jsp_string19, 0, _jsp_string19.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 7932908523769947432L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("texas/feedback/feedback_list.jsp"), 7197088641398259062L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("PAGER"), new com.caucho.el.StringLiteral("items")), "PAGER.items");
  private final static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("one"), new com.caucho.el.StringLiteral("id")), "one.id");
  private final static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("one"), new com.caucho.el.StringLiteral("app_id")), "one.app_id");
  private final static com.caucho.el.Expr _caucho_expr_3 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("one"), new com.caucho.el.StringLiteral("user_id")), "one.user_id");
  private final static com.caucho.el.Expr _caucho_expr_4 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("one"), new com.caucho.el.StringLiteral("message")), "one.message");
  private final static com.caucho.el.Expr _caucho_expr_5 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("one"), new com.caucho.el.StringLiteral("question_type")), "one.question_type");
  private final static com.caucho.el.Expr _caucho_expr_6 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("one"), new com.caucho.el.StringLiteral("status")), "one.status"), new com.caucho.el.LongLiteral(0L));
  private final static com.caucho.el.Expr _caucho_expr_7 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("one"), new com.caucho.el.StringLiteral("status")), "one.status"), new com.caucho.el.LongLiteral(1L));
  private final static com.caucho.el.Expr _caucho_expr_8 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("one"), new com.caucho.el.StringLiteral("status")), "one.status"), new com.caucho.el.LongLiteral(2L));
  private final static com.caucho.el.Expr _caucho_expr_9 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("one"), new com.caucho.el.StringLiteral("create_time")), "one.create_time");

  private final static char []_jsp_string10;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string11;
  private final static char []_jsp_string12;
  private final static char []_jsp_string14;
  private final static char []_jsp_string2;
  private final static char []_jsp_string19;
  private final static char []_jsp_string16;
  private final static char []_jsp_string0;
  private final static char []_jsp_string7;
  private final static char []_jsp_string9;
  private final static char []_jsp_string15;
  private final static char []_jsp_string6;
  private final static char []_jsp_string13;
  private final static char []_jsp_string8;
  private final static char []_jsp_string17;
  private final static char []_jsp_string18;
  private final static char []_jsp_string4;
  private final static char []_jsp_string3;
  static {
    _jsp_string10 = "\r\n	                 	<td>\u65b0\u7559\u8a00    <a onclick=\"openNewWinow('feedback.do?method=loadByID&iscancel=1&id=".toCharArray();
    _jsp_string5 = "</a></td>\r\n	                 <td><a onclick=\"openNewWinow('feedback.do?method=query&user_id=".toCharArray();
    _jsp_string1 = "\r\n					\r\n				<tr id=\"tr_".toCharArray();
    _jsp_string11 = "')\">\u56de\u590d</a></td>\r\n	                 ".toCharArray();
    _jsp_string12 = "\r\n	                 ".toCharArray();
    _jsp_string14 = "\r\n	                 	<td>\u5df2\u56de\u590d</td>\r\n	                 ".toCharArray();
    _jsp_string2 = "\">\r\n										\r\n					<td><a onclick=\"openNewWinow('feedback.do?method=loadByID&iscancel=1&id=".toCharArray();
    _jsp_string19 = "\r\n		\r\n	</div>	\r\n</div>\r\n<div id=\"ami_newwindow\" style=\"display: none;\">\r\n\r\n</div>\r\n\r\n<script type=\"text/javascript\">\r\n	function openframe(url,title)\r\n	{\r\n		url=geturl(url);\r\n		$('#frame').attr('src','');\r\n		$('#page_title_nav').html(title);\r\n		\r\n		$('#div_frame').show();\r\n		$('#PAGECONTENT').hide();\r\n		$('#frame').attr('src',url);\r\n		$('.ami_Mask').hide();	\r\n	}\r\n\r\nfunction doDelete(id)\r\n{\r\n	\r\n	bootbox.confirm(\"Delete this Feedback?\", function(result) {\r\n		if(result) {\r\n			\r\n			$('.ami_Mask').show();\r\n			var url=\"feedback.do?method=delByID&id=\"+id;\r\n			$.get(url, function(data){\r\n				\r\n				$('.ami_Mask').hide();\r\n				$('#tr_'+id).remove();\r\n				bootbox.alert(data);	\r\n				\r\n			});						\r\n		}\r\n	});	\r\n}\r\n\r\n</script>".toCharArray();
    _jsp_string16 = "</td>\r\n	                \r\n					<td>\r\n						<div class='hidden-phone visible-desktop btn-group'>						\r\n							<button class='btn btn-mini btn-danger' onclick=\"doDelete('".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n<hr/>\r\n			<form class=\"form-inline\" action=\"feedback.do?method=query\" id=\"searchForm\">\r\n			</form>\r\n\r\n<div id=\"ami_main\">\r\n<div class=\"row-fluid\">\r\n	<span class=\"ami_table_header_title\">Feedback List</span>\r\n\r\n		<table id=\"table_report\" class=\"table table-striped table-bordered table-hover\">\r\n			<thead>			\r\n				<tr>\r\n					<th>ID</th>\r\n					<th>App ID</th>\r\n					<th>User ID</th>\r\n					<th style=\"width:20%\">Message</th>\r\n					<th>Feedback Type</th>\r\n					\r\n					<th>Status</th>	\r\n					<th>Create Time</th>\r\n\r\n					<th>\u7ba1\u7406</th>\r\n				</tr>				\r\n			</thead>\r\n			<tbody>				\r\n				  ".toCharArray();
    _jsp_string7 = "</a></td>\r\n	                 <td><a onclick=\"openNewWinow('feedback.do?method=loadByID&iscancel=1&id=".toCharArray();
    _jsp_string9 = "</td>\r\n	                                 \r\n	                 ".toCharArray();
    _jsp_string15 = "\r\n	                 <td>".toCharArray();
    _jsp_string6 = "&appid=".toCharArray();
    _jsp_string13 = "\r\n	                 	<td>\u65b0\u56de\u590d    <a onclick=\"openNewWinow('feedback.do?method=loadByID&iscancel=1&id=".toCharArray();
    _jsp_string8 = "</a></td>\r\n	                 <td>".toCharArray();
    _jsp_string17 = "')\"><i class='icon-trash'></i></button>						\r\n						</div>\r\n					</td>\r\n				</tr>\r\n				\r\n			  ".toCharArray();
    _jsp_string18 = "\r\n					\r\n			</tbody>\r\n		</table>		\r\n		".toCharArray();
    _jsp_string4 = "</a></td>\r\n					<td><a onclick=\"openNewWinow('feedback.do?method=query&appid=".toCharArray();
    _jsp_string3 = "')\">".toCharArray();
  }
}
